// node build.mjs — builds the model, checks it, and writes every output.
//   out/brickroom.ldr   LDraw model with STEP markers (open in LeoCAD, Studio, LPub3D)
//   out/parts.csv       parts list
//   out/bricklink.xml   BrickLink wanted list (upload at bricklink.com/v2/wanted/upload.page)
//   out/report.md       validation report
//   web/model.js        model data for the game and the build viewer

import { writeFileSync, mkdirSync } from 'node:fs';
import { PARTS, COLORS, BASEPLATE } from './lib/catalog.mjs';
import { createScene, realize, makeSteps } from './lib/builder.mjs';
import { validate } from './lib/validate.mjs';
import { describe, PLAYER_START, STALL, CRATE_FLOOR_Y, OBJECT_LABELS } from './scene.mjs';

const SIZE = BASEPLATE.size;
const { S, reqs, objects } = createScene();
describe(S);
const parts = realize(reqs);
const steps = makeSteps(parts, objects);
const report = validate(parts, steps, SIZE);

mkdirSync('out', { recursive: true });

// LDraw: 1 stud = 20 LDU, 1 plate = 8 LDU, -Y is up, part origin at its top centre.
const ROT_Z = '0 0 -1 0 1 0 1 0 0';
const ID = '1 0 0 0 1 0 0 0 1';
const ldr = [
  '0 Brickroom: the playroom',
  '0 Name: brickroom.ldr',
  '0 Author: Claudette (Claude Opus 5.5)',
  '0 !LICENSE Not for redistribution',
  '',
  `1 19 ${SIZE * 10} 0 ${SIZE * 10} ${ID} ${BASEPLATE.id}.dat`,
  '0 STEP',
];
for (const s of steps) {
  ldr.push(`0 // ${OBJECT_LABELS[s.obj]}`);
  for (const i of s.parts) {
    const p = parts[i];
    const X = (p.x + p.w / 2) * 20;
    const Z = (p.z + p.d / 2) * 20;
    const Y = -(p.y + p.h) * 8;
    ldr.push(`1 ${p.color} ${X} ${Y} ${Z} ${p.w < p.d ? ROT_Z : ID} ${p.part}.dat`);
  }
  ldr.push('0 STEP');
}
writeFileSync('out/brickroom.ldr', ldr.join('\r\n') + '\r\n');

// Parts list, baseplate included.
const counts = new Map([[`${BASEPLATE.id}|19`, 1]]);
for (const p of parts) counts.set(`${p.part}|${p.color}`, (counts.get(`${p.part}|${p.color}`) || 0) + 1);
const rows = [...counts.entries()]
  .map(([k, qty]) => {
    const [part, color] = k.split('|');
    const name = part === BASEPLATE.id ? BASEPLATE.name : PARTS[part].name;
    return { part, name, color: +color, qty };
  })
  .sort((a, b) => b.qty - a.qty || a.part.localeCompare(b.part));
writeFileSync(
  'out/parts.csv',
  'part,name,color,ldraw_color,bricklink_color,qty\n' +
    rows.map((r) => `${r.part},${r.name},${COLORS[r.color].name},${r.color},${COLORS[r.color].bl},${r.qty}`).join('\n') + '\n',
);
writeFileSync(
  'out/bricklink.xml',
  '<INVENTORY>\n' +
    rows
      .map((r) => `  <ITEM><ITEMTYPE>P</ITEMTYPE><ITEMID>${r.part}</ITEMID><COLOR>${COLORS[r.color].bl}</COLOR><MINQTY>${r.qty}</MINQTY></ITEM>`)
      .join('\n') +
    '\n</INVENTORY>\n',
);

// Floor cells the minifig can stand on: nothing below minifig height (10 plates),
// except flat floor coverings and the toys themselves.
const walk = [];
for (let z = 0; z < SIZE; z++) {
  const row = new Array(SIZE).fill(1);
  walk.push(row);
}
for (const p of parts) {
  if (p.obj === 'rug' || p.obj === 'toys' || p.y >= 10) continue;
  for (let x = p.x; x < p.x + p.w; x++) for (let z = p.z; z < p.z + p.d; z++) walk[z][x] = 0;
}
const fruit = new Set(parts.filter((p) => p.obj === 'stall' && p.y === CRATE_FLOOR_Y && p.part === '4073').map((p) => `${p.x},${p.z}`));
const slots = [];
for (const z of [11, 13]) for (const x of [14, 15, 17, 18, 20, 21]) if (!fruit.has(`${x},${z}`)) slots.push([x, z]);

const total = rows.reduce((s, r) => s + r.qty, 0);
const model = {
  size: SIZE,
  colors: Object.fromEntries(Object.entries(COLORS).map(([k, v]) => [k, { name: v.name, hex: v.hex }])),
  partNames: Object.fromEntries(Object.entries(PARTS).map(([k, v]) => [k, v.name])),
  objectLabels: OBJECT_LABELS,
  parts: parts.map((p) => {
    const P = PARTS[p.part];
    const o = { p: p.part, c: p.color, x: p.x, y: p.y, z: p.z, w: p.w, d: p.d, h: p.h, o: p.obj };
    if (P.round) o.r = 1;
    if (P.studs) o.s = 1;
    if (p.toy) o.t = p.toy;
    return o;
  }),
  steps: steps.map((s) => ({ o: s.obj, p: s.parts })),
  walk: walk.map((r) => r.join('')),
  start: PLAYER_START,
  stall: STALL,
  slots,
  crateY: CRATE_FLOOR_Y,
  stats: {
    parts: total,
    studConnections: report.studConnections,
    collisions: report.collisions,
    floating: report.floating,
    unbuildable: report.unbuildable,
    steps: report.steps,
  },
};
mkdirSync('web', { recursive: true });
writeFileSync('web/model.js', `window.BRICKROOM = ${JSON.stringify(model)};\n`);

const md = [
  '# Brickroom validation report',
  '',
  `Generated by \`node build.mjs\`. Result: **${report.ok ? 'PASS' : 'FAIL'}**`,
  '',
  `- Parts: ${total} (${parts.length} placed + 1 baseplate), ${rows.length} part/colour lots`,
  `- Stud connections: ${report.studConnections}`,
  `- Collisions: ${report.collisions}`,
  `- Parts not connected to the baseplate: ${report.floating}`,
  `- Parts with nothing to click onto when placed: ${report.unbuildable}`,
  `- Instruction steps: ${report.steps}`,
  `- Stacked parts that bridge two or more parts below: ${(report.bondedShare * 100).toFixed(0)}%`,
  '',
  '## Balance (centre of mass over the ground footprint)',
  '',
  ...Object.entries(report.balance).map(
    ([o, b]) => `- ${OBJECT_LABELS[o]}: centre (${b.com.join(', ')}), footprint x ${b.footprint[0]}–${b.footprint[2]}, z ${b.footprint[1]}–${b.footprint[3]}: ${b.inside ? 'OK' : 'OUTSIDE'}`,
  ),
  '',
  '## Issues',
  '',
  ...(report.issues.length ? report.issues.map((s) => `- ${s}`) : ['None.']),
  '',
];
writeFileSync('out/report.md', md.join('\n'));

console.log(md.slice(0, 11).join('\n'));
if (report.issues.length) console.log(report.issues.slice(0, 20).join('\n'));
process.exit(report.ok ? 0 : 1);
